### ISSUE TITLE
var declarations for pre-existing properties on Object.prototype

### ISSUE THREAD

**Issue by ziyunfei** [anba/es6draft#1]
```javascript
js> var __proto__ = 1
js> __proto__ === Object.prototype
true
```

```javascript
js> let __proto__ = 1
js> __proto__ === 1
true
```

```javascript
js> Object.defineProperty(Object.prototype, "foo", {set(v){print("set foo =", v)}})
{}
js> var foo = 1
set foo = 1
```
@anba  Is this intentional or a bug? Thanks!

**Comment by anba** [comment]
The results are correct when compared to the current spec draft (rev31), unfortunately the 'why' is a bit tricky to explain. Let me give it a try:

> js> var \_\_proto\_\_ = 1
> js> \_\_proto\_\_ === Object.prototype
> true

`var __proto__ = 1` consists of two parts `var __proto__` and `__proto__ = 1`. For `var __proto__` we need to check [15.1.8 GlobalDeclarationInstantiation](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-globaldeclarationinstantiation), specifically steps 6, 12 and 17. Step 6 validates the new `var` binding named `__proto__` won't clash with an existing lexical declaration, this validation will succeed. Step 12 validates the `var` binding can be installed on the global object; a `var` binding can be installed if the global object is either extensible or alternatively a property with the same name is already present on the global object or its prototype chain ([8.1.1.4.15 CanDeclareGlobalVar](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-candeclareglobalvar)). And the `__proto__` property is present on the global object prototype chain if the global object inherits from `Object.prototype`! Finally step 17 of GlobalDeclarationInstantiation tries to create the global `var` binding ([8.1.1.4.17 CreateGlobalVarBinding](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-createglobalvarbinding)), in this case no new property is created, because a `__proto__` property is already present on the global object prototype chain (, but `__proto__` gets still marked as `var` binding by adding it to the global environment record `VarNames` list!).
The other part `__proto__ = 1` is just a normal expression statement, so it consists of resolving the reference and executing PutValue on that reference. Eventually will end up in [B.2.2.1.2 set Object.prototype.\_\_proto\_\_](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-set-object.prototype.__proto__) where we simply exit the function in step 4, because the argument value is not a valid prototype value.

> 
> js> let \_\_proto\_\_ = 1
> js> \_\_proto\_\_ === 1
> true

[15.1.8 GlobalDeclarationInstantiation](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-globaldeclarationinstantiation), specifically steps 5 and 15. All three validation checks in step 5 succeed, so step 15 is able to create a global lexical binding. When resolving the identifier reference in `__proto__ === 1`, the global lexical bindings are resolved before global var bindings ([8.1.1.4.6 GetBindingValue](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-global-environment-records-getbindingvalue-n-s)), which means `__proto__` resolves to the lexical declaration created in `let __proto__`. 

> 
> js> Object.defineProperty(Object.prototype, "foo", {set(v){print("set foo =", v)}})
> {}
> js> var foo = 1
> set foo = 1

This is basically the same as `var __proto__`.

**Comment by anba** [comment]
Btw, I have no idea whether or not the current spec algorithm is actually web compatible. It may turn out to be not compatible...

**Comment by ziyunfei** [comment]
Neither do I, but maybe @tschneidereit  does.

**Comment by tschneidereit** [comment]
Yeah, good question. It'll certainly break sites, but I'm moderately optimistic about that being manageable. The browser `Window` global certainly is riddles with insanity :(

FWIW, matching `let`'s behavior in SpiderMonkey is tracked in [bug 589199](https://bugzilla.mozilla.org/show_bug.cgi?id=589199), waiting in @jswalden's review/feedback queue.
