### ISSUE TITLE
Do you have something like docs?

### ISSUE THREAD

**Issue by NE-SmallTown** [anba/es6draft#21]
I'm reading your code and trying to understand, I konw you write the code base on ecmascript specification, but there are some terms or explaination that I can't understand.

So I want to know whether you have some extra docs to help me to understand, thank you very much.

**Comment by anba** [comment]
No, there aren't any additional docs. There are some terms which stem from earlier ECMAScript drafts or were used on the es-discuss mailing list to describe things which aren't resp. weren't part of the official specification at that point. For example the current source code in this repo is still using the term "Task" instead of "Job" (https://tc39.github.io/ecma262/#sec-jobs-and-job-queues). Or there's "World" to describe the set of connected realms (this term was used on es-discuss a few years ago).

**Comment by NE-SmallTown** [comment]
@anba Thanks for your reply.I notice that you don't have commit in github recently,so until just now I don't think your will answer this question.As you say,next time I meet something about term,I will ask for help on es-discuss,althought I find it just one day after I post this question.But,thanks again.

**Comment by anba** [comment]
I'm currently focusing on other projects, so I don't have enough time to work on this code base. I still have some local changes, though. Maybe I find the time to clean them up and publish them later this year!

**Comment by NE-SmallTown** [comment]
@anba oh,that's sounds great!I am hoping for that.
